/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Book_1.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BookTest(props) {
  const { nodes, materials } = useGLTF('/Book_1.gltf')
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('/Book_1.gltf')
